version: '3.9'

services:
  snapshot_api:
    image: snapshot_api
    build: .
    restart: always
    command: uvicorn main:app --reload --host 0.0.0.0 --port 80
    env_file: .env
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./app:/code/app/
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    command: redis-server
    hostname: redis
    ports:
      - '${REDIS_PORT}:6379'
